# Generated by Django 4.1.7 on 2023-03-15 05:25

import camera.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default=camera.models.generate_random_id, max_length=100, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('model_number', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('store_id', models.UUIDField(null=True)),
                ('operation_status', models.CharField(max_length=100, null=True)),
                ('associated_machines', models.CharField(max_length=100, null=True)),
                ('rtmp_path', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
            },
        ),
        migrations.CreateModel(
            name='Scanners',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=100, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('store_id', models.CharField(max_length=100, null=True)),
                ('operation_status', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scanner',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(max_length=50)),
                ('end_time', models.DateTimeField(max_length=50)),
                ('session_id', models.UUIDField()),
                ('video_path_local', models.TextField()),
                ('video_path_cloud', models.TextField()),
                ('machine_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Video',
            },
        ),
    ]
