# Generated by Django 4.1.7 on 2023-03-15 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('weight_change_events', models.TextField()),
                ('store_session', models.TextField()),
                ('user_id', models.UUIDField()),
                ('user_session_id', models.UUIDField()),
                ('video', models.TextField()),
                ('machine_id', models.CharField(max_length=100, null=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
            },
        ),
    ]
